### ISSUE TITLE
[Fix] 전체복용 버튼 오류 수정

### ISSUE THREAD

**Issue by JIWON1923** [DeveloperAcademy-POSTECH/MC3-Team2-APillog#215]
### 문제 상황
- 약을 새로 등록 한 후, 메인으로 돌아왔을 때 전체 복용 버튼이 회색으로 보임
- 약의 복용을 끄고, 메인으로 돌아왔을 때 전체복용 버튼이 초록색으로 보임. 하단 영상 참고해주세요

https://user-images.githubusercontent.com/68676844/185787752-cacaf565-5253-49de-b6a3-35b1d8c55db6.MP4

### TODO
- [x] 오류 해결하기

### 참고
- delegate나 뷰 생명주기를 이용해서 해결하면 좋을 것 같아요!

**Comment by mycookie1** [comment]
겹치는 부분이 있어서 제가 합니다~
